name: $(GitVersion.FullSemVer)

trigger:
  - master

pr:
  - master

jobs:
  - job: "Windows_PS51_BuildTest"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: GitVersion@4
        displayName: "Run GitVersion"
      - powershell: ./tools/build.ps1
        displayName: "Execute Build"
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release"
        inputs:
          PathtoPublish: Release
          ArtifactName: Release
      - task: PublishTestResults@2
        displayName: "Publish Pester test results"
        inputs:
          testRunner: "NUnit"
          testResultsFiles: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
          testRunTitle: 'Windows PS5.1 Tests'
        condition: succeededOrFailed()

  - job: "Linux_PSCore_Test"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: PowerShell@2
        displayName: "Execute Tests"
        inputs:
          targetType: "filePath"
          filePath: ./tools/build.ps1
          arguments: "-Task Test"
          pwsh: true
      - task: PublishTestResults@2
        displayName: "Publish Pester test results"
        inputs:
          testRunner: "NUnit"
          testResultsFiles: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
          testRunTitle: 'Linux PSCore Tests'
        condition: succeededOrFailed()
