pool:
  vmImage: vs2017-win2016

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(System.DefaultWorkingDirectory)\tools\Run-PesterInVSTS.ps1'
      arguments: '-outputFile $(System.DefaultWorkingDirectory)\Test-Pester.XML'
      continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testRunner: 'NUnit'
      testResultsFiles: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
