pool:
  vmImage: vs2017-win2016

name: $(GitVersion.FullSemVer)

steps:
  - task: GitVersion@4
    displayName: "Run GitVersion"

  - task: Pester@8
    displayName: "Pester Test Runner"

  - task: PublishTestResults@2
    displayName: "Publish Pester test results"
    inputs:
      testRunner: "NUnit"
      testResultsFiles: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
