name: $(GitVersion.FullSemVer)

trigger:
  - master

pr:
  - master

jobs:
  - job: "GitVersion"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: GitVersion@4
        displayName: "Run GitVersion"

  - job: "Windows_PS5.1_BuildTest"
    dependsOn: "GitVersion"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - powershell: ./tools/build.ps1
        displayName: "Execute Build"
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release"
        inputs:
          PathtoPublish: Release
          ArtifactName: Release
      - task: PublishTestResults@2
        displayName: "Publish Pester test results"
        inputs:
          testRunner: "NUnit"
          testResultsFiles: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
        condition: succeededOrFailed()

  - job: "Linux_PSCore_Test"
    dependsOn: "GitVersion"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: PowerShell@2
        displayName: "Execute Tests"
        inputs:
          targetType: "filePath"
          filePath: ./tools/build.ps1
          arguments: "-Task Test"
          pwsh: true
