pool:
  vmImage: vs2017-win2016

name: $(GitVersion.FullSemVer)

steps:
  - powershell: |
      Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
      Install-Module -Name PSScriptAnalyzer -Force -Verbose -Scope CurrentUser
    displayName: "Install PS Modules"

  - task: GitVersion@4
    displayName: "Run GitVersion"

  - task: Pester@8
    displayName: "Pester Test Runner"

  - task: PublishTestResults@2
    displayName: "Publish Pester test results"
    inputs:
      testRunner: "NUnit"
      testResultsFiles: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
    condition: succeededOrFailed()
